#!/usr/bin/env bash
# Script that configure Nginx server so that
# /redirect_me is redirecting to another page.

apt update -y && apt upgrade -y
apt install nginx -y

# Index page
echo "Hello World!" >/var/www/html/index.nginx-debian.html

# Redirect to "301 Moved Permanently"
sed -i '/listen \[::\]:80 default_server;/a\        rewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4' /etc/nginx/sites-available/default

service nginx restart
