#!/usr/bin/env bash
# Bash script that setup a nginx web server on our server, redirection, 404, header

apt update -y && apt upgrade -y
apt install nginx -y
sudo ufw allow 'Nginx HTTP'

# Index page
sudo echo "Hello World!" >/var/www/html/index.nginx-debian.html

# Redirect to a wonderful Nyan Cat page
sudo sed -i 's/server_name _;/server_name _;\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-available/default

# 404 Page not found
sudo echo "Ceci n'est pas une pagee" >/usr/share/nginx/html/custom_404.html
sudo sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default

# Served header
sudo sed -i "/404 \/404.html;$/a\        add_header X-Served-By $(hostname);" /etc/nginx/sites-available/default

sudo service nginx restart
sudo service nginx reload
