#!/usr/bin/env bash
# Bash script that Install and configure HAproxy on your lb-01 server.
apt update -y && apt upgrade -y
apt-get install --no-install-recommends software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-2.7 -y
apt-get install haproxy=2.7.\* -y

echo "ENABLED=1" >>/etc/default/haproxy

haproxy_cfg="\nbackend web-backend\n\tbalance roundrobin\n\tserver 124573-web-01 100.26.228.181:80 check\n\tserver 124573-web-02 35.153.17.79:80 check\n\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend"

echo -e "$haproxy_cfg" >>/etc/haproxy/haproxy.cfg

service haproxy restart
