#!/usr/bin/env bash
# Bash script that Install and configure HAproxy on your lb-01 server.
sudo apt update -y && sudo apt upgrade -y
sudo apt install haproxy -y

echo "ENABLED=1" | sudo tee /etc/default/haproxy

haproxy_cfg="\nbackend web-backend\n  balance roundrobin\n  server 124573-web-01 100.26.228.181:80 check\n  server 124573-web-02 35.153.17.79:80 check\n\nfrontend http\n  bind *:80\n  mode http\n  default_backend web-backend"

echo -e "$haproxy_cfg" | sudo tee /etc/haproxy/haproxy.cfg

sudo service haproxy restart
