#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.
touch /hosts.new
echo "localhost	127.0.0.2" >> /hosts.new
echo "facebook.com	8.8.8.8" >> /hosts.new
echo "$(cat~/hosts.new)" > /etc/hosts
